### ISSUE TITLE
Sugestão de Reestruturação

### ISSUE THREAD

**Issue by gustavo-depaula** [asantos07/oisumida#4]
Algumas sugestões para o app.
* *Mudança de nome* Pensei em SecretLens, o que acha?
* *Stack*: React + Firebase. Em vez de fazer o backend, usar auth & database via firebase;

**Comment by ariel-codes** [comment]
Já tô reestruturando, o app vai ser em React Native msm, se eu conseguir integrar a API do Expo pra mapas direito. O backend foi simplificado: so MongoDB e Socket.io, possivelmente até sem o Socket. Também resolvi usar TypeScript no back pra deixar mais organizado e testável.

A ideia é manter sem login, totalmente anônimo msm.

O nome é interessante, bora abrir uma votação em algum lugar.

**Comment by ariel-codes** [comment]
# Vote num nome:
(usando as reacts)
- SecretLens (Laugh)
- Speculum (Hooray)
- Heimdallr (Confused)
- Teçá (Heart)

**Comment by ibryans** [comment]
😂

**Comment by alandeivson** [comment]
😂

**Comment by gustavo-depaula** [comment]
😂
O que significa esses outros nomes?

**Comment by ariel-codes** [comment]
Em retrospecto, SecretLens é brega dms, neim

**Comment by ariel-codes** [comment]
_Speculum_: Lente, espelho (em latim)
_Heimdallr_: Deus nórdico que vê tudo
_Teçá_: "olhos atentos" ou algo do tipo em Tupi

**Comment by ariel-codes** [comment]
@gustavo-depaula SecretLens é mto brega pô :(
